apiVersion: v1
kind: Service
metadata:
  name: store
  namespace: ai-documention
  labels:
    app.kubernetes.io/name: ai-documention
    app.kubernetes.io/instance: store
    app.kubernetes.io/version: "0.0.1"
spec:
  type: ClusterIP
  ports:
    - name: default
      port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app.kubernetes.io/name: ai-documention
    app.kubernetes.io/instance: store
  internalTrafficPolicy: Cluster
