apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: ai-documention
  labels:
    app.kubernetes.io/name: ai-documention
    app.kubernetes.io/instance: collector
    app.kubernetes.io/version: "0.0.1"

spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-documention
      app.kubernetes.io/instance: collector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-documention
        app.kubernetes.io/instance: collector

    spec:
      containers:
        - name: collector
          image: "jmgoyesc/ai-collector:0.0.3"
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: store
            - name: KUBESHARK_WEBSOCKET_HOST
              value: "kubeshark-hub.kubeshark"
          ports:
            - name: default
              containerPort: 8050
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8050
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8050
