apiVersion: apps/v1
kind: Deployment
metadata:
  name: viewer
  namespace: ai-documention
  labels:
    app.kubernetes.io/name: ai-documention
    app.kubernetes.io/instance: viewer
    app.kubernetes.io/version: "0.0.1"

spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-documention
      app.kubernetes.io/instance: viewer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-documention
        app.kubernetes.io/instance: viewer

    spec:
      containers:
        - name: viewer
          image: "jmgoyesc/ai-viewer:0.0.1"
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_DATA_MONGODB_HOST
              value: store
          ports:
            - name: default
              containerPort: 8052
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8052
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8052
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
